Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,7 +32,7 @@ jobs:
       - name: Start Gunicorn
         run: |
           # Ensure your app path is correct
-          gunicorn --bind 0.0.0.0:8001 app:app --daemon  # Update port to 8001
+          gunicorn --bind 0.0.0.0:8000 app:app --daemon  # Update port to 8001
 
       # Set up Nginx configuration
       - name: Set up Nginx configuration
@@ -46,7 +46,7 @@ jobs:
               listen 80;
               server_name 54.161.43.43;  # Replace with your actual EC2 IP or domain
               location / {
-                  proxy_pass http://127.0.0.1:8001;  # Update to the new port 8001
+                  proxy_pass http://127.0.0.1:8000;  # Update to the new port 8001
                   proxy_set_header Host \$host;
                   proxy_set_header X-Real-IP \$remote_addr;
                   proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
@@ -71,7 +71,7 @@ jobs:
       - name: Check application health
         run: |
           # Check health on localhost
-          curl -s http://127.0.0.1:8001/health || echo "Application health check failed"
+          curl -s http://127.0.0.1:8000/health || echo "Application health check failed"
           
           # Replace <your-ec2-ip> with your actual EC2 IP or domain for public access check
-          curl -s http://54.161.43.43:8001 || echo "Public IP health check failed"
+          curl -s http://54.161.43.43:8000 || echo "Public IP health check failed"
